version: '3'

services:
    app:
        image: node:18.17-alpine
        working_dir: /app
        tty: true
        volumes:
            - .:/app
        environment:
            - WATCHPACK_POLLING=true
        command: sh -c "npm ci && npm run dev"
        ports:
            - '3010:3000'
